# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QLabel, QLayout, QListView,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QTextBrowser, QToolBox, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(960, 750)
        MainWindow.setMinimumSize(QSize(960, 750))
        MainWindow.setMaximumSize(QSize(960, 750))
        self.actionCOM1 = QAction(MainWindow)
        self.actionCOM1.setObjectName(u"actionCOM1")
        self.action_5 = QAction(MainWindow)
        self.action_5.setObjectName(u"action_5")
        self.actionCamera1 = QAction(MainWindow)
        self.actionCamera1.setObjectName(u"actionCamera1")
        self.actionCamera2 = QAction(MainWindow)
        self.actionCamera2.setObjectName(u"actionCamera2")
        self.actionStart = QAction(MainWindow)
        self.actionStart.setObjectName(u"actionStart")
        self.actionStop = QAction(MainWindow)
        self.actionStop.setObjectName(u"actionStop")
        self.actionRescan = QAction(MainWindow)
        self.actionRescan.setObjectName(u"actionRescan")
        self.actionAudio1 = QAction(MainWindow)
        self.actionAudio1.setObjectName(u"actionAudio1")
        self.actionAudio2 = QAction(MainWindow)
        self.actionAudio2.setObjectName(u"actionAudio2")
        self.actionRescan_2 = QAction(MainWindow)
        self.actionRescan_2.setObjectName(u"actionRescan_2")
        self.actionMute = QAction(MainWindow)
        self.actionMute.setObjectName(u"actionMute")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lblCameraFrame = QLabel(self.centralwidget)
        self.lblCameraFrame.setObjectName(u"lblCameraFrame")
        self.lblCameraFrame.setGeometry(QRect(10, 10, 640, 360))
        self.lblCameraFrame.setFrameShape(QFrame.StyledPanel)
        self.lblCameraFrame.setFrameShadow(QFrame.Plain)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 380, 641, 81))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 25, 30, 26))
        self.label_3.setMinimumSize(QSize(30, 0))
        self.label_3.setMaximumSize(QSize(30, 16777215))
        self.cbxCameraList = QComboBox(self.groupBox)
        self.cbxCameraList.setObjectName(u"cbxCameraList")
        self.cbxCameraList.setGeometry(QRect(50, 25, 240, 26))
        self.cbxCameraList.setMinimumSize(QSize(240, 0))
        self.cbxCameraList.setMaximumSize(QSize(240, 16777215))
        self.btnCapture = QPushButton(self.groupBox)
        self.btnCapture.setObjectName(u"btnCapture")
        self.btnCapture.setGeometry(QRect(290, 23, 60, 26))
        self.btnCapture.setMinimumSize(QSize(60, 0))
        self.btnCapture.setMaximumSize(QSize(60, 16777215))
        self.btnRescan = QPushButton(self.groupBox)
        self.btnRescan.setObjectName(u"btnRescan")
        self.btnRescan.setGeometry(QRect(550, 25, 80, 50))
        self.btnRescan.setMinimumSize(QSize(80, 0))
        self.btnRescan.setMaximumSize(QSize(60, 16777215))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(370, 25, 30, 26))
        self.label_2.setMinimumSize(QSize(30, 0))
        self.label_2.setMaximumSize(QSize(30, 16777215))
        self.cbxFps = QComboBox(self.groupBox)
        self.cbxFps.setObjectName(u"cbxFps")
        self.cbxFps.setGeometry(QRect(410, 25, 60, 26))
        self.cbxFps.setMaximumSize(QSize(60, 40))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 50, 30, 26))
        self.label_6.setMinimumSize(QSize(30, 0))
        self.label_6.setMaximumSize(QSize(30, 16777215))
        self.cbxAudioList = QComboBox(self.groupBox)
        self.cbxAudioList.setObjectName(u"cbxAudioList")
        self.cbxAudioList.setGeometry(QRect(50, 50, 240, 26))
        self.cbxAudioList.setMinimumSize(QSize(240, 0))
        self.cbxAudioList.setMaximumSize(QSize(240, 16777215))
        self.chkMute = QCheckBox(self.groupBox)
        self.chkMute.setObjectName(u"chkMute")
        self.chkMute.setGeometry(QRect(290, 50, 87, 26))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 465, 641, 251))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 25, 30, 26))
        self.label_4.setMinimumSize(QSize(30, 0))
        self.label_4.setMaximumSize(QSize(30, 16777215))
        self.cbxSerialList = QComboBox(self.groupBox_2)
        self.cbxSerialList.setObjectName(u"cbxSerialList")
        self.cbxSerialList.setGeometry(QRect(50, 25, 240, 26))
        self.cbxSerialList.setMinimumSize(QSize(240, 0))
        self.cbxSerialList.setMaximumSize(QSize(240, 16777215))
        self.btnSerialRescan = QPushButton(self.groupBox_2)
        self.btnSerialRescan.setObjectName(u"btnSerialRescan")
        self.btnSerialRescan.setGeometry(QRect(550, 20, 80, 35))
        self.btnSerialRescan.setMinimumSize(QSize(80, 0))
        self.btnSerialRescan.setMaximumSize(QSize(60, 16777215))
        self.label_r = QLabel(self.groupBox_2)
        self.label_r.setObjectName(u"label_r")
        self.label_r.setGeometry(QRect(470, 90, 60, 25))
        self.label_r.setAutoFillBackground(False)
        self.label_r.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_r.setAlignment(Qt.AlignCenter)
        self.label_lstick_press = QLabel(self.groupBox_2)
        self.label_lstick_press.setObjectName(u"label_lstick_press")
        self.label_lstick_press.setGeometry(QRect(128, 118, 19, 19))
        self.label_lstick_press.setAutoFillBackground(False)
        self.label_lstick_press.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_lstick_press.setAlignment(Qt.AlignCenter)
        self.label_action = QLabel(self.groupBox_2)
        self.label_action.setObjectName(u"label_action")
        self.label_action.setGeometry(QRect(20, 220, 521, 20))
        self.label_dpad_b = QLabel(self.groupBox_2)
        self.label_dpad_b.setObjectName(u"label_dpad_b")
        self.label_dpad_b.setGeometry(QRect(200, 190, 25, 25))
        self.label_dpad_b.setAutoFillBackground(False)
        self.label_dpad_b.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_dpad_b.setAlignment(Qt.AlignCenter)
        self.label_zl = QLabel(self.groupBox_2)
        self.label_zl.setObjectName(u"label_zl")
        self.label_zl.setGeometry(QRect(20, 63, 71, 25))
        self.label_zl.setAutoFillBackground(False)
        self.label_zl.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_zl.setAlignment(Qt.AlignCenter)
        self.label_home = QLabel(self.groupBox_2)
        self.label_home.setObjectName(u"label_home")
        self.label_home.setGeometry(QRect(310, 108, 25, 25))
        self.label_home.setAutoFillBackground(False)
        self.label_home.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_home.setAlignment(Qt.AlignCenter)
        self.label_lstick_b = QLabel(self.groupBox_2)
        self.label_lstick_b.setObjectName(u"label_lstick_b")
        self.label_lstick_b.setGeometry(QRect(125, 140, 25, 25))
        self.label_lstick_b.setAutoFillBackground(False)
        self.label_lstick_b.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_lstick_b.setAlignment(Qt.AlignCenter)
        self.label_zr = QLabel(self.groupBox_2)
        self.label_zr.setObjectName(u"label_zr")
        self.label_zr.setGeometry(QRect(470, 63, 71, 25))
        self.label_zr.setAutoFillBackground(False)
        self.label_zr.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_zr.setAlignment(Qt.AlignCenter)
        self.label_rstick_b = QLabel(self.groupBox_2)
        self.label_rstick_b.setObjectName(u"label_rstick_b")
        self.label_rstick_b.setGeometry(QRect(335, 190, 25, 25))
        self.label_rstick_b.setAutoFillBackground(False)
        self.label_rstick_b.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_rstick_b.setAlignment(Qt.AlignCenter)
        self.label_rstick_l = QLabel(self.groupBox_2)
        self.label_rstick_l.setObjectName(u"label_rstick_l")
        self.label_rstick_l.setGeometry(QRect(310, 165, 25, 25))
        self.label_rstick_l.setAutoFillBackground(False)
        self.label_rstick_l.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_rstick_l.setAlignment(Qt.AlignCenter)
        self.label_lstick_t = QLabel(self.groupBox_2)
        self.label_lstick_t.setObjectName(u"label_lstick_t")
        self.label_lstick_t.setGeometry(QRect(125, 90, 25, 25))
        self.label_lstick_t.setAutoFillBackground(False)
        self.label_lstick_t.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_lstick_t.setAlignment(Qt.AlignCenter)
        self.label_y = QLabel(self.groupBox_2)
        self.label_y.setObjectName(u"label_y")
        self.label_y.setGeometry(QRect(385, 115, 25, 25))
        self.label_y.setAutoFillBackground(False)
        self.label_y.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_y.setAlignment(Qt.AlignCenter)
        self.label_b = QLabel(self.groupBox_2)
        self.label_b.setObjectName(u"label_b")
        self.label_b.setGeometry(QRect(410, 140, 25, 25))
        self.label_b.setAutoFillBackground(False)
        self.label_b.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_b.setAlignment(Qt.AlignCenter)
        self.label_rstick_r = QLabel(self.groupBox_2)
        self.label_rstick_r.setObjectName(u"label_rstick_r")
        self.label_rstick_r.setGeometry(QRect(360, 165, 25, 25))
        self.label_rstick_r.setAutoFillBackground(False)
        self.label_rstick_r.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_rstick_r.setAlignment(Qt.AlignCenter)
        self.label_rstick_press = QLabel(self.groupBox_2)
        self.label_rstick_press.setObjectName(u"label_rstick_press")
        self.label_rstick_press.setGeometry(QRect(338, 168, 19, 19))
        self.label_rstick_press.setAutoFillBackground(False)
        self.label_rstick_press.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_rstick_press.setAlignment(Qt.AlignCenter)
        self.label_lstick_r = QLabel(self.groupBox_2)
        self.label_lstick_r.setObjectName(u"label_lstick_r")
        self.label_lstick_r.setGeometry(QRect(150, 115, 25, 25))
        self.label_lstick_r.setAutoFillBackground(False)
        self.label_lstick_r.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_lstick_r.setAlignment(Qt.AlignCenter)
        self.label_dpad_l = QLabel(self.groupBox_2)
        self.label_dpad_l.setObjectName(u"label_dpad_l")
        self.label_dpad_l.setGeometry(QRect(175, 165, 25, 25))
        self.label_dpad_l.setAutoFillBackground(False)
        self.label_dpad_l.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_dpad_l.setAlignment(Qt.AlignCenter)
        self.label_plus = QLabel(self.groupBox_2)
        self.label_plus.setObjectName(u"label_plus")
        self.label_plus.setGeometry(QRect(335, 83, 25, 25))
        self.label_plus.setAutoFillBackground(False)
        self.label_plus.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_plus.setAlignment(Qt.AlignCenter)
        self.label_minus = QLabel(self.groupBox_2)
        self.label_minus.setObjectName(u"label_minus")
        self.label_minus.setGeometry(QRect(200, 83, 25, 25))
        self.label_minus.setAutoFillBackground(False)
        self.label_minus.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_minus.setAlignment(Qt.AlignCenter)
        self.label_x = QLabel(self.groupBox_2)
        self.label_x.setObjectName(u"label_x")
        self.label_x.setGeometry(QRect(410, 90, 25, 25))
        self.label_x.setAutoFillBackground(False)
        self.label_x.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_x.setAlignment(Qt.AlignCenter)
        self.label_lstick_l = QLabel(self.groupBox_2)
        self.label_lstick_l.setObjectName(u"label_lstick_l")
        self.label_lstick_l.setGeometry(QRect(100, 115, 25, 25))
        self.label_lstick_l.setAutoFillBackground(False)
        self.label_lstick_l.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_lstick_l.setAlignment(Qt.AlignCenter)
        self.label_dpad_r = QLabel(self.groupBox_2)
        self.label_dpad_r.setObjectName(u"label_dpad_r")
        self.label_dpad_r.setGeometry(QRect(225, 165, 25, 25))
        self.label_dpad_r.setAutoFillBackground(False)
        self.label_dpad_r.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_dpad_r.setAlignment(Qt.AlignCenter)
        self.label_rstick_t = QLabel(self.groupBox_2)
        self.label_rstick_t.setObjectName(u"label_rstick_t")
        self.label_rstick_t.setGeometry(QRect(335, 140, 25, 25))
        self.label_rstick_t.setAutoFillBackground(False)
        self.label_rstick_t.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_rstick_t.setAlignment(Qt.AlignCenter)
        self.label_capture = QLabel(self.groupBox_2)
        self.label_capture.setObjectName(u"label_capture")
        self.label_capture.setGeometry(QRect(225, 108, 25, 25))
        self.label_capture.setAutoFillBackground(False)
        self.label_capture.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_capture.setAlignment(Qt.AlignCenter)
        self.label_a = QLabel(self.groupBox_2)
        self.label_a.setObjectName(u"label_a")
        self.label_a.setGeometry(QRect(435, 115, 25, 25))
        self.label_a.setAutoFillBackground(False)
        self.label_a.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_a.setAlignment(Qt.AlignCenter)
        self.label_dpad_t = QLabel(self.groupBox_2)
        self.label_dpad_t.setObjectName(u"label_dpad_t")
        self.label_dpad_t.setGeometry(QRect(200, 140, 25, 25))
        self.label_dpad_t.setAutoFillBackground(False)
        self.label_dpad_t.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_dpad_t.setAlignment(Qt.AlignCenter)
        self.label_l = QLabel(self.groupBox_2)
        self.label_l.setObjectName(u"label_l")
        self.label_l.setGeometry(QRect(30, 90, 60, 25))
        self.label_l.setAutoFillBackground(False)
        self.label_l.setStyleSheet(u"background-color:rgb(170, 170, 170)")
        self.label_l.setAlignment(Qt.AlignCenter)
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(660, 400, 291, 316))
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(660, 10, 291, 361))
        self.toolBox = QToolBox(self.groupBox_3)
        self.toolBox.setObjectName(u"toolBox")
        self.toolBox.setGeometry(QRect(10, 20, 271, 331))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(0, 0, 271, 223))
        self.cbxJoystickList = QComboBox(self.page)
        self.cbxJoystickList.setObjectName(u"cbxJoystickList")
        self.cbxJoystickList.setGeometry(QRect(50, 10, 211, 26))
        self.cbxJoystickList.setMinimumSize(QSize(0, 0))
        self.cbxJoystickList.setMaximumSize(QSize(16777215, 16777215))
        self.label_5 = QLabel(self.page)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 10, 30, 26))
        self.label_5.setMinimumSize(QSize(30, 0))
        self.label_5.setMaximumSize(QSize(30, 16777215))
        self.btnJoystickRescan = QPushButton(self.page)
        self.btnJoystickRescan.setObjectName(u"btnJoystickRescan")
        self.btnJoystickRescan.setGeometry(QRect(180, 40, 80, 35))
        self.btnJoystickRescan.setMinimumSize(QSize(80, 0))
        self.btnJoystickRescan.setMaximumSize(QSize(60, 16777215))
        self.toolBox.addItem(self.page, u"\u5b9e\u65f6\u63a7\u5236")
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setGeometry(QRect(0, 0, 271, 223))
        self.listView = QListView(self.page_2)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(0, 10, 271, 171))
        self.pushButton = QPushButton(self.page_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(192, 190, 81, 32))
        self.toolBox.addItem(self.page_2, u"\u5185\u7f6e\u811a\u672c")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_7 = QLabel(self.page_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 251, 91))
        self.label_7.setFrameShape(QFrame.StyledPanel)
        self.label_7.setLineWidth(0)
        self.label_7.setMidLineWidth(0)
        self.label_7.setTextFormat(Qt.AutoText)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.pushButton_2 = QPushButton(self.page_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 110, 71, 32))
        self.pushButton_3 = QPushButton(self.page_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(200, 110, 71, 32))
        self.toolBox.addItem(self.page_3, u"\u5916\u90e8\u811a\u672c")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.toolBox.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"NS\u63a7\u5236\u53f0", None))
        self.actionCOM1.setText(QCoreApplication.translate("MainWindow", u"COM1", None))
        self.action_5.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0", None))
        self.actionCamera1.setText(QCoreApplication.translate("MainWindow", u"Camera1", None))
        self.actionCamera2.setText(QCoreApplication.translate("MainWindow", u"Camera2", None))
        self.actionStart.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.actionRescan.setText(QCoreApplication.translate("MainWindow", u"Rescan", None))
        self.actionAudio1.setText(QCoreApplication.translate("MainWindow", u"Audio1", None))
        self.actionAudio2.setText(QCoreApplication.translate("MainWindow", u"Audio2", None))
        self.actionRescan_2.setText(QCoreApplication.translate("MainWindow", u"Rescan", None))
        self.actionMute.setText(QCoreApplication.translate("MainWindow", u"Mute", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.lblCameraFrame.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u91c7\u96c6\u8bbe\u5907", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891:", None))
        self.btnCapture.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe", None))
        self.btnRescan.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22\u8bbe\u5907", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"FPS:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u9891:", None))
        self.chkMute.setText(QCoreApplication.translate("MainWindow", u"\u9759\u97f3", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"\u63a7\u5236\u8bbe\u5907", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907:", None))
        self.btnSerialRescan.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22\u8bbe\u5907", None))
        self.label_r.setText(QCoreApplication.translate("MainWindow", u"R u", None))
        self.label_lstick_press.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.label_action.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u65f6\u547d\u4ee4\uff1a", None))
        self.label_dpad_b.setText(QCoreApplication.translate("MainWindow", u"\u4e0b v", None))
        self.label_zl.setText(QCoreApplication.translate("MainWindow", u"ZL q", None))
        self.label_home.setText(QCoreApplication.translate("MainWindow", u"H h", None))
        self.label_lstick_b.setText(QCoreApplication.translate("MainWindow", u"s", None))
        self.label_zr.setText(QCoreApplication.translate("MainWindow", u"ZR o", None))
        self.label_rstick_b.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.label_rstick_l.setText(QCoreApplication.translate("MainWindow", u",", None))
        self.label_lstick_t.setText(QCoreApplication.translate("MainWindow", u"w", None))
        self.label_y.setText(QCoreApplication.translate("MainWindow", u"Y j", None))
        self.label_b.setText(QCoreApplication.translate("MainWindow", u"B k", None))
        self.label_rstick_r.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.label_rstick_press.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.label_lstick_r.setText(QCoreApplication.translate("MainWindow", u"d", None))
        self.label_dpad_l.setText(QCoreApplication.translate("MainWindow", u"\u5de6 c", None))
        self.label_plus.setText(QCoreApplication.translate("MainWindow", u"+ y", None))
        self.label_minus.setText(QCoreApplication.translate("MainWindow", u"- r", None))
        self.label_x.setText(QCoreApplication.translate("MainWindow", u"X i", None))
        self.label_lstick_l.setText(QCoreApplication.translate("MainWindow", u"a", None))
        self.label_dpad_r.setText(QCoreApplication.translate("MainWindow", u"\u53f3 b", None))
        self.label_rstick_t.setText(QCoreApplication.translate("MainWindow", u";", None))
        self.label_capture.setText(QCoreApplication.translate("MainWindow", u"C g", None))
        self.label_a.setText(QCoreApplication.translate("MainWindow", u"A l", None))
        self.label_dpad_t.setText(QCoreApplication.translate("MainWindow", u"\u4e0a f", None))
        self.label_l.setText(QCoreApplication.translate("MainWindow", u"L e", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\u8f93\u5165\u65b9\u5f0f", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u624b\u67c4:", None))
        self.btnJoystickRescan.setText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22\u8bbe\u5907", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QCoreApplication.translate("MainWindow", u"\u5b9e\u65f6\u63a7\u5236", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QCoreApplication.translate("MainWindow", u"\u5185\u7f6e\u811a\u672c", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u672a\u9009\u62e9\u6587\u4ef6", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u542f\u52a8", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QCoreApplication.translate("MainWindow", u"\u5916\u90e8\u811a\u672c", None))
    # retranslateUi

