# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'win.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1260, 810)
        MainWindow.setMinimumSize(QSize(1260, 590))
        MainWindow.setMaximumSize(QSize(1260, 810))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(970, 5, 231, 32))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(1210, 5, 41, 32))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 960, 540))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(680, 580, 280, 158))
        self.label_lstick_t = QLabel(self.centralwidget)
        self.label_lstick_t.setObjectName(u"label_lstick_t")
        self.label_lstick_t.setGeometry(QRect(180, 600, 30, 30))
        self.label_lstick_t.setAutoFillBackground(False)
        self.label_lstick_t.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_lstick_t.setAlignment(Qt.AlignCenter)
        self.label_lstick_b = QLabel(self.centralwidget)
        self.label_lstick_b.setObjectName(u"label_lstick_b")
        self.label_lstick_b.setGeometry(QRect(180, 660, 30, 30))
        self.label_lstick_b.setAutoFillBackground(False)
        self.label_lstick_b.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_lstick_b.setAlignment(Qt.AlignCenter)
        self.label_lstick_l = QLabel(self.centralwidget)
        self.label_lstick_l.setObjectName(u"label_lstick_l")
        self.label_lstick_l.setGeometry(QRect(150, 630, 30, 30))
        self.label_lstick_l.setAutoFillBackground(False)
        self.label_lstick_l.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_lstick_l.setAlignment(Qt.AlignCenter)
        self.label_lstick_r = QLabel(self.centralwidget)
        self.label_lstick_r.setObjectName(u"label_lstick_r")
        self.label_lstick_r.setGeometry(QRect(210, 630, 30, 30))
        self.label_lstick_r.setAutoFillBackground(False)
        self.label_lstick_r.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_lstick_r.setAlignment(Qt.AlignCenter)
        self.label_dpad_t = QLabel(self.centralwidget)
        self.label_dpad_t.setObjectName(u"label_dpad_t")
        self.label_dpad_t.setGeometry(QRect(250, 650, 30, 30))
        self.label_dpad_t.setAutoFillBackground(False)
        self.label_dpad_t.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_dpad_t.setAlignment(Qt.AlignCenter)
        self.label_dpad_l = QLabel(self.centralwidget)
        self.label_dpad_l.setObjectName(u"label_dpad_l")
        self.label_dpad_l.setGeometry(QRect(220, 680, 30, 30))
        self.label_dpad_l.setAutoFillBackground(False)
        self.label_dpad_l.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_dpad_l.setAlignment(Qt.AlignCenter)
        self.label_dpad_r = QLabel(self.centralwidget)
        self.label_dpad_r.setObjectName(u"label_dpad_r")
        self.label_dpad_r.setGeometry(QRect(280, 680, 30, 30))
        self.label_dpad_r.setAutoFillBackground(False)
        self.label_dpad_r.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_dpad_r.setAlignment(Qt.AlignCenter)
        self.label_dpad_b = QLabel(self.centralwidget)
        self.label_dpad_b.setObjectName(u"label_dpad_b")
        self.label_dpad_b.setGeometry(QRect(250, 710, 30, 30))
        self.label_dpad_b.setAutoFillBackground(False)
        self.label_dpad_b.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_dpad_b.setAlignment(Qt.AlignCenter)
        self.label_rstick_l = QLabel(self.centralwidget)
        self.label_rstick_l.setObjectName(u"label_rstick_l")
        self.label_rstick_l.setGeometry(QRect(360, 680, 30, 30))
        self.label_rstick_l.setAutoFillBackground(False)
        self.label_rstick_l.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rstick_l.setAlignment(Qt.AlignCenter)
        self.label_rstick_r = QLabel(self.centralwidget)
        self.label_rstick_r.setObjectName(u"label_rstick_r")
        self.label_rstick_r.setGeometry(QRect(420, 680, 30, 30))
        self.label_rstick_r.setAutoFillBackground(False)
        self.label_rstick_r.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rstick_r.setAlignment(Qt.AlignCenter)
        self.label_rstick_t = QLabel(self.centralwidget)
        self.label_rstick_t.setObjectName(u"label_rstick_t")
        self.label_rstick_t.setGeometry(QRect(390, 650, 30, 30))
        self.label_rstick_t.setAutoFillBackground(False)
        self.label_rstick_t.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rstick_t.setAlignment(Qt.AlignCenter)
        self.label_rstick_b = QLabel(self.centralwidget)
        self.label_rstick_b.setObjectName(u"label_rstick_b")
        self.label_rstick_b.setGeometry(QRect(390, 710, 30, 30))
        self.label_rstick_b.setAutoFillBackground(False)
        self.label_rstick_b.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rstick_b.setAlignment(Qt.AlignCenter)
        self.label_y = QLabel(self.centralwidget)
        self.label_y.setObjectName(u"label_y")
        self.label_y.setGeometry(QRect(430, 630, 30, 30))
        self.label_y.setAutoFillBackground(False)
        self.label_y.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_y.setAlignment(Qt.AlignCenter)
        self.label_x = QLabel(self.centralwidget)
        self.label_x.setObjectName(u"label_x")
        self.label_x.setGeometry(QRect(460, 600, 30, 30))
        self.label_x.setAutoFillBackground(False)
        self.label_x.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_x.setAlignment(Qt.AlignCenter)
        self.label_a = QLabel(self.centralwidget)
        self.label_a.setObjectName(u"label_a")
        self.label_a.setGeometry(QRect(490, 630, 30, 30))
        self.label_a.setAutoFillBackground(False)
        self.label_a.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_a.setAlignment(Qt.AlignCenter)
        self.label_b = QLabel(self.centralwidget)
        self.label_b.setObjectName(u"label_b")
        self.label_b.setGeometry(QRect(460, 660, 30, 30))
        self.label_b.setAutoFillBackground(False)
        self.label_b.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_b.setAlignment(Qt.AlignCenter)
        self.label_plus = QLabel(self.centralwidget)
        self.label_plus.setObjectName(u"label_plus")
        self.label_plus.setGeometry(QRect(380, 590, 30, 30))
        self.label_plus.setAutoFillBackground(False)
        self.label_plus.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_plus.setAlignment(Qt.AlignCenter)
        self.label_minus = QLabel(self.centralwidget)
        self.label_minus.setObjectName(u"label_minus")
        self.label_minus.setGeometry(QRect(260, 590, 30, 30))
        self.label_minus.setAutoFillBackground(False)
        self.label_minus.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_minus.setAlignment(Qt.AlignCenter)
        self.label_home = QLabel(self.centralwidget)
        self.label_home.setObjectName(u"label_home")
        self.label_home.setGeometry(QRect(350, 620, 30, 30))
        self.label_home.setAutoFillBackground(False)
        self.label_home.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_home.setAlignment(Qt.AlignCenter)
        self.label_capture = QLabel(self.centralwidget)
        self.label_capture.setObjectName(u"label_capture")
        self.label_capture.setGeometry(QRect(290, 620, 30, 30))
        self.label_capture.setAutoFillBackground(False)
        self.label_capture.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_capture.setAlignment(Qt.AlignCenter)
        self.label_lstick_press = QLabel(self.centralwidget)
        self.label_lstick_press.setObjectName(u"label_lstick_press")
        self.label_lstick_press.setGeometry(QRect(185, 635, 20, 20))
        self.label_lstick_press.setAutoFillBackground(False)
        self.label_lstick_press.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_lstick_press.setAlignment(Qt.AlignCenter)
        self.label_rstick_press = QLabel(self.centralwidget)
        self.label_rstick_press.setObjectName(u"label_rstick_press")
        self.label_rstick_press.setGeometry(QRect(395, 685, 20, 20))
        self.label_rstick_press.setAutoFillBackground(False)
        self.label_rstick_press.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_rstick_press.setAlignment(Qt.AlignCenter)
        self.label_l = QLabel(self.centralwidget)
        self.label_l.setObjectName(u"label_l")
        self.label_l.setGeometry(QRect(80, 600, 60, 25))
        self.label_l.setAutoFillBackground(False)
        self.label_l.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_l.setAlignment(Qt.AlignCenter)
        self.label_zl = QLabel(self.centralwidget)
        self.label_zl.setObjectName(u"label_zl")
        self.label_zl.setGeometry(QRect(70, 570, 71, 25))
        self.label_zl.setAutoFillBackground(False)
        self.label_zl.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_zl.setAlignment(Qt.AlignCenter)
        self.label_r = QLabel(self.centralwidget)
        self.label_r.setObjectName(u"label_r")
        self.label_r.setGeometry(QRect(530, 600, 60, 25))
        self.label_r.setAutoFillBackground(False)
        self.label_r.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_r.setAlignment(Qt.AlignCenter)
        self.label_zr = QLabel(self.centralwidget)
        self.label_zr.setObjectName(u"label_zr")
        self.label_zr.setGeometry(QRect(529, 570, 71, 25))
        self.label_zr.setAutoFillBackground(False)
        self.label_zr.setStyleSheet(u"background-color:rgb(209, 209, 209)")
        self.label_zr.setAlignment(Qt.AlignCenter)
        self.label_action = QLabel(self.centralwidget)
        self.label_action.setObjectName(u"label_action")
        self.label_action.setGeometry(QRect(70, 740, 531, 20))
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(970, 50, 281, 721))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1260, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb", None))
        self.label.setText("")
        self.label_2.setText("")
        self.label_lstick_t.setText(QCoreApplication.translate("MainWindow", u"(w)", None))
        self.label_lstick_b.setText(QCoreApplication.translate("MainWindow", u"(s)", None))
        self.label_lstick_l.setText(QCoreApplication.translate("MainWindow", u"(a)", None))
        self.label_lstick_r.setText(QCoreApplication.translate("MainWindow", u"(d)", None))
        self.label_dpad_t.setText(QCoreApplication.translate("MainWindow", u"\u4e0a(f)", None))
        self.label_dpad_l.setText(QCoreApplication.translate("MainWindow", u"\u5de6(c)", None))
        self.label_dpad_r.setText(QCoreApplication.translate("MainWindow", u"\u53f3(b)", None))
        self.label_dpad_b.setText(QCoreApplication.translate("MainWindow", u"\u4e0b(v)", None))
        self.label_rstick_l.setText(QCoreApplication.translate("MainWindow", u"(,)", None))
        self.label_rstick_r.setText(QCoreApplication.translate("MainWindow", u"(/)", None))
        self.label_rstick_t.setText(QCoreApplication.translate("MainWindow", u"(;)", None))
        self.label_rstick_b.setText(QCoreApplication.translate("MainWindow", u"(.)", None))
        self.label_y.setText(QCoreApplication.translate("MainWindow", u"Y(j)", None))
        self.label_x.setText(QCoreApplication.translate("MainWindow", u"X(i)", None))
        self.label_a.setText(QCoreApplication.translate("MainWindow", u"A(l)", None))
        self.label_b.setText(QCoreApplication.translate("MainWindow", u"B(k)", None))
        self.label_plus.setText(QCoreApplication.translate("MainWindow", u"+(y)", None))
        self.label_minus.setText(QCoreApplication.translate("MainWindow", u"-(r)", None))
        self.label_home.setText(QCoreApplication.translate("MainWindow", u"H(h)", None))
        self.label_capture.setText(QCoreApplication.translate("MainWindow", u"C(g)", None))
        self.label_lstick_press.setText(QCoreApplication.translate("MainWindow", u"(x)", None))
        self.label_rstick_press.setText(QCoreApplication.translate("MainWindow", u"(')", None))
        self.label_l.setText(QCoreApplication.translate("MainWindow", u"L(e)", None))
        self.label_zl.setText(QCoreApplication.translate("MainWindow", u"ZL(q)", None))
        self.label_r.setText(QCoreApplication.translate("MainWindow", u"R(u)", None))
        self.label_zr.setText(QCoreApplication.translate("MainWindow", u"ZR(o)", None))
        self.label_action.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u65f6\u547d\u4ee4\uff1a", None))
    # retranslateUi

